development:
  adapter: postgresql
  encoding: unicode
  database: bsc_online_development
  pool: 5
  username: bsc_online
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: bsc_online_test
  pool: 5
  username: bsc_online
  password: