# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18efef2447e606f1136dbab5fd2e63afe084419b780d706786919d41a196625250f556c22e6894c0fd42971279a47495c4fe0730c7909c2aaa038c2c3395546a

test:
  secret_key_base: de2e28af4fb9a4a77de76bcedf019c2b1d2982db88538d89681f6d2a35dd3feb146df673cfa9b0bc2e688466d5c1662f8cd2c6d2b843818bddec1bf541361cc4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
